/* This file was auto-generated by KreMLin! */
#ifndef __Test_H
#define __Test_H



#include "kremlib.h"

uint32_t Test_read_length(uint8_t *buf, uint32_t len);

bool Test_parse_len(uint8_t *buf, uint32_t len, uint32_t *out_len);
#endif
